### ISSUE TITLE
Add information abour required `permissions`

### ISSUE THREAD

**Issue by TobKed** [TobKed/github_actions_oidc#1]
mssing information about

```yaml
permissions:
  id-token: write  # This is required for aws-actions/configure-aws-credentials
  contents: write  # This is required for actions/checkout
```

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
